### ISSUE TITLE
Does this extension hide reactions on Facebook posts?

### ISSUE THREAD

**Issue by nafiz1001** [WesleyBranton/Facebook-Like-Hider#17]
Just want to be sure that by reactions you mean something like this:
![image](https://user-images.githubusercontent.com/15523177/112676818-4e240780-8e3f-11eb-80a0-d212a6e16322.png)
Because I could still see reactions from those kinds of posts.

**Comment by WesleyBranton** [comment]
Yes, this extension is able to hide the reactions counter on the post. The like/reaction counter is in the top-left of your provided screenshot. If you set the "Like/reaction counters" option to "hide", that should stop those from appearing on posts and comments.

When making a change to the extension settings, you need to make sure to reload Facebook for the changes to be applied. If that doesn't work, try restarting Firefox.

**Comment by nafiz1001** [comment]
It works. Thank you so much for your work!

**Comment by WesleyBranton** [comment]
No problem! Glad I could help!
